resources/public/api/conf/1.4/application.yaml

This scope *should* allow us to deploy now.

Add TGP scope to OpenApi Spec

---

build.sbt
run_local.sh

Added the default port number as per service manager.  Also added a run_local.sh file which will run the API locally starting all the services from service manager

added portnumber as in the service manager

---

resources/public/api/conf/1.0/application.yaml

- Added field references under **components/schemas** section
- Renamed fields from snake_case to camelCase
- Updated definitions (description, minLength, maxLength, etc.)

TGP-482: refactored API spec and updated create TGP record endpoint

---

resources/public/api/conf/1.0/application.yaml

Now Create, Update and items in Get use a common RecordResponse schema keeping them aligned.
Added pagination fields to the Get response schema

Move record response to common component add pagination to schema

---

resources/public/api/conf/1.0/application.yaml

- Added multiple records example for get TGP record
- Added error examples

TGP 639 Update API spec

---

app/uk/gov/hmrc/tradergoodsprofiles/controllers/actions/AuthAction.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordControllerIntegrationSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/actions/AuthActionSpec.scala

Updates to the error descriptions based no comments in https://jira.tools.tax.service.gov.uk/browse/TGP-633

TGP-633 Update error descriptions

---

resources/public/api/conf/1.0/application.yaml

- New Request Accreditation endpoint
- Added operationId to Remove TGP record endpoint
- Included regex patterns for eori, actorId and countryOfOrigin fields
- Added enums to category and declarable fields
- Updated descriptions

TGP-641 add Request Accreditation endpoint

---

resources/public/api/conf/1.0/application.yaml

- Removed references to X-Client-ID from headers
- Corrected description for EORI param

TGP-920 Removed X-Client-ID from headers

---

resources/public/api/conf/1.0/application.yaml

- Added operationId
- Removed eori from request body
- Updated description and summary

TGP-642 Add operationId and remove eori from request body

---

README.md
app/uk/gov/hmrc/tradergoodsprofiles/connectors/BaseConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/RouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordController.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/requests/UpdateRecordRequest.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/requests/router/RouterCreateRecordRequest.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/requests/router/RouterUpdateRecordRequest.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/responses/CreateOrUpdateRecordResponse.scala
app/uk/gov/hmrc/tradergoodsprofiles/services/RouterService.scala
conf/app.routes
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordControllerIntegrationSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/RouteConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/support/requests/RouterUpdateRecordRequestSupport.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/support/requests/UpdateRecordRequestSupport.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/support/responses/CreateOrUpdateRecordResponseSupport.scala
test/uk/gov/hmrc/tradergoodsprofiles/services/RouterServiceSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/utils/ValidationSupportSpec.scala

Implemented Update Record endpoint

[TGP-423] Implement Update Record endpoint

---

app/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/actions/AuthAction.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/actions/ValidateHeaderAction.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/actions/AuthActionSpec.scala

Refactoring following som of Wolfy suggestions

refactoring

---

app/uk/gov/hmrc/tradergoodsprofiles/models/requests/RequestAccreditationRequest.scala

Added validation for request filed not covered by router validations

TGP-850 request-accreditation-fix

---

app/uk/gov/hmrc/tradergoodsprofiles/connectors/RouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/services/RouterService.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordControllerIntegrationSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/RouteConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/services/RouterServiceSpec.scala

Changed URL router for the Create Record. Also done some refactory

TGP-1267: change url for the router for create record

---

build.sbt

Based on this page: https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=176632503

Disable plugin based on confluence advice

---

resources/public/api/conf/1.0/application.yaml

update the requestorEmail max length and minor corrections

TGP-1347: update the requestorEmail max length and minor corrections

---

app/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordController.scala
app/uk/gov/hmrc/tradergoodsprofiles/utils/ApplicationConstants.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerIntegrationSpec.scala
resources/public/api/conf/1.0/application.yaml
test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerSpec.scala

TGP-1375: Update API spec for Remove record endpoint and resolve minor bugs

---

app/uk/gov/hmrc/tradergoodsprofiles/connectors/RouterConnector.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerIntegrationSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/RouterConnectorSpec.scala

TGP-1315: Update router paths

---

resources/public/api/conf/1.0/application.yaml

Reverts hmrc/trader-goods-profiles#104

Revert "TGP-1011: implement withdraw advice endpoint" for time being for TSS testing

---

resources/public/api/definition.json

Based on this confluence: https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=928220471

Remove the scopes section

---

app/uk/gov/hmrc/tradergoodsprofiles/config/AppConfig.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/BaseConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/RemoveRecordRouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordController.scala
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordControllerIntegrationSpec.scala
test/config/AppConfigSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/CreateRecordRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/GetRecordsRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/MaintainProfileRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/RemoveRecordRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/UpdateRecordRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordControllerSpec.scala

Need to be merged with https://github.com/hmrc/trader-goods-profiles-router/pull/116

TGP-2364: Rename feature flag for client id and set default value to true

---

app/uk/gov/hmrc/tradergoodsprofiles/models/responses/CreateOrUpdateRecordResponse.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/responses/GetRecordResponse.scala
app/uk/gov/hmrc/tradergoodsprofiles/models/responses/ReviewReason.scala
app/uk/gov/hmrc/tradergoodsprofiles/utils/ResponseModelSupport.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/support/responses/GetRecordResponseSupport.scala
test/uk/gov/hmrc/tradergoodsprofiles/models/GetRecordResponseSpec.scala

1. Wait for pipeline to pass
2. Move ticket to QA column in Jira
3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

TGP-3272 - refactor ReviewReason

---

app/uk/gov/hmrc/tradergoodsprofiles/connectors/BaseConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/GetRecordsRouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/RemoveRecordRouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/connectors/UpdateRecordRouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileController.scala
app/uk/gov/hmrc/tradergoodsprofiles/controllers/UpdateRecordController.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileControllerIntegrationSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerIntegrationSpec.scala
project/AppDependencies.scala
test/uk/gov/hmrc/tradergoodsprofiles/connectors/RemoveRecordRouterConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/CreateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/GetRecordsControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/MaintainProfileControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofiles/controllers/RemoveRecordControllerSpec.scala

1. Wait for pipeline to pass
2. Move ticket to QA column in Jira
3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

TGP-3480 - remove comments after investigation completed

---

build.sbt
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

1. Wait for pipeline to pass
2. Move ticket to QA column in Jira
3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

TGP-3506 - remove HttpClient from application.conf

---

project/AppDependencies.scala
project/plugins.sbt

1. Wait for pipeline to pass
2. Move ticket to QA column in Jira
3. Leave message in tgp-qa on slack to alert QAs that this ticket is ready for testing

TGP-3523: update dependencies
